version: "3.4"

services:
  deephaven:
    build: .
    ports:
      - "${DEEPHAVEN_PORT:-10000}:10000"
    volumes:
      - ./data:/data
    environment:
      - START_OPTS=-Xmx4g -Ddeephaven.application.dir=/data/app.d -Dauthentication.psk=${DH_PSK}
      - WEAVIATE_ENDPOINT=${WEAVIATE_ENDPOINT}
      - WEAVIATE_TOKEN=${WEAVIATE_TOKEN}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
